"""[CPOS Phase 1] Sensor event envelope and Task Tape adapter.

Implements only the part of `docs/EVENT_BUS_AND_WORLD_MODEL_SPEC.md` and
`docs/SENSOR_AND_GOAL_MANAGER_SPEC.md` that the Git sensor needs: the
`kagioneko.sensor_event.v1` record shape, its safety invariants, and the
adapter that writes conforming records onto the CPOS Task Tape.

Out of scope here: the Goal Manager, the World Model, and the other
`kagioneko.cognitive_event.v1` event types. This module exists so the
Event Bus boundary is a named seam rather than an implicit one, not to
start those components.

The contract is closed at every level. The top-level field set is frozen
(`FIELD_TYPES`). Each `source` has a static `SensorContract` that freezes
its event vocabulary, its subject form, and the exact typed key set of its
`observation`. Provenance is schema-driven: a field the contract marks as
untrusted must be named in `untrusted_fields` whenever it is present, and
nothing else may be. There is no registration API, so the set of accepted
producers cannot be widened at runtime.
"""

import math
import re
import uuid
from datetime import datetime, timezone
from typing import Any, Callable, Dict, List, Optional, Tuple

SENSOR_EVENT_SCHEMA = "kagioneko.sensor_event.v1"

# Task Tape event name for a recorded sensor observation, from the
# "Suggested CPOS event names" list in the Event Bus spec.
TAPE_SENSOR_EVENT = "cognitive_sensor_event_recorded"

RISK_LEVELS = ("low", "medium", "high", "critical")

# Every field the Event Bus spec pins to a fixed value for a metadata-only
# sensor record. These are invariants of the Phase 1 sensor layer, not
# per-event choices, so the builder sets them and the validator enforces them.
SAFETY_INVARIANTS = {
    "metadata_only": True,
    "raw_request_stored": False,
    "raw_diff_stored": False,
    "raw_outputs_stored": False,
    "secret_values_stored": False,
    "execute_automatically": False,
}

# The complete, frozen top-level field set with its required type. Anything
# absent from this mapping is rejected: an unknown field would otherwise ride
# through the adapter into persistent storage and defeat the boundary.
FIELD_TYPES: Dict[str, Any] = {
    "schema": str,
    "event_id": str,
    "event_type": str,
    "sensor_event_type": str,
    "source": str,
    "observed_at": str,
    "subject": str,
    "summary": str,
    "risk": str,
    "confidence": float,
    "source_of_truth": list,
    "requires_human_review": bool,
    "suggested_next_action": str,
    # Contract-level provenance: dotted paths naming fields whose value is
    # written by an untrusted producer (a repository, a remote peer). Which
    # paths must appear here is decided by the source's contract, not by
    # the producer.
    "untrusted_fields": list,
    "metadata_only": bool,
    "raw_request_stored": bool,
    "raw_diff_stored": bool,
    "raw_outputs_stored": bool,
    "secret_values_stored": bool,
    "execute_automatically": bool,
    # Additive extension: the state labels and counts the Event Bus spec tells
    # sensors to store. Its exact key set is fixed per source, below.
    "observation": dict,
}

REQUIRED_FIELDS = tuple(f for f in FIELD_TYPES if f != "observation")

# Logical pointers only. An absolute host path, a URL with credentials, or a
# free-form string is not a source of truth the tape may carry.
# A segment is a bounded identifier; dot-only segments (`.`, `..`) are refused.
_SEGMENT = r"(?!\.+(?:/|$))[A-Za-z0-9_.\-]+"
SOURCE_OF_TRUTH_PATTERN = re.compile(rf"^ptr://{_SEGMENT}(?:/{_SEGMENT})*$")
MAX_SOURCE_OF_TRUTH_LEN = 200
MAX_SOURCE_OF_TRUTH_ENTRIES = 8

MAX_TEXT_LEN = 512          # summary, subject, suggested_next_action
MAX_OBSERVATION_STR_LEN = 256

# Shared identifier grammar for repository keys and similar handles.
IDENT = r"[A-Za-z0-9_-]{1,64}"

# `event_id` is always producer-generated by `build_sensor_event`, never by a
# caller, so its shape is exact rather than merely length-bounded.
EVENT_ID_PATTERN = re.compile(r"^sensor_evt_[0-9a-f]{16}$")

# RFC3339 timestamp, the form every sensor uses (`datetime.isoformat()`).
# Bounded so an unbounded/garbage string cannot ride through as a trusted
# top-level field just because it happens to be a `str`.
RFC3339_PATTERN = r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,6})?(Z|[+-]\d{2}:\d{2})$"
MAX_OBSERVED_AT_LEN = 40


class SensorEventContractError(ValueError):
    """A record does not conform to `kagioneko.sensor_event.v1`."""


# --- per-source contracts ------------------------------------------------

class ObservationField:
    """One allowlisted observation key: its type, nullability, and provenance."""

    __slots__ = ("type", "nullable", "untrusted", "pattern")

    def __init__(self, type_, *, nullable=False, untrusted=False, pattern=None):
        self.type = type_
        self.nullable = nullable
        self.untrusted = untrusted
        self.pattern = re.compile(pattern) if pattern else None


class SensorContract:
    """Everything a given `source` is allowed to put on the tape."""

    __slots__ = (
        "source", "event_types", "subject_pattern", "observation",
        "observation_optional_types", "placeholder_subject",
        "placeholder_subject_types", "invariants", "observation_invariant",
    )

    def __init__(
        self, source, event_types, subject_pattern, observation,
        observation_optional_types=(), placeholder_subject=None,
        placeholder_subject_types=(), invariants=None,
        observation_invariant=None,
    ):
        self.source = source
        self.event_types = frozenset(event_types)
        self.subject_pattern = re.compile(subject_pattern)
        self.observation: Dict[str, ObservationField] = dict(observation)
        # Event types allowed to carry no `observation` at all: sensor faults,
        # not observations of the watched system. Every other event type in
        # `event_types` must carry the full, exact observation shape.
        self.observation_optional_types = frozenset(observation_optional_types)
        # A fixed placeholder subject value (e.g. an "invalid key" marker) is
        # only legitimate alongside the fault path that produces it, never
        # attached to a real observation by an alternate producer.
        self.placeholder_subject = placeholder_subject
        self.placeholder_subject_types = frozenset(placeholder_subject_types)
        # Per-event-type semantic invariant over `observation`, so the
        # contract enforces what `sensor_event_type` claims, not just its
        # shape (e.g. `git_clean` actually requires a clean reading).
        self.invariants: Dict[str, Callable[[Dict[str, Any]], bool]] = dict(invariants or {})
        # Type-independent self-consistency of `observation`: fields that
        # must agree with each other regardless of which event type carries
        # them (e.g. an untracked count cannot exceed the total dirty count).
        self.observation_invariant: Optional[Callable[[Dict[str, Any]], bool]] = observation_invariant

    @property
    def untrusted_paths(self) -> Tuple[str, ...]:
        return tuple(f"observation.{k}" for k, f in self.observation.items() if f.untrusted)


def _git_observation_is_self_consistent(obs: Dict[str, Any]) -> bool:
    """Fields that must agree regardless of `sensor_event_type`.

    `ahead`/`behind` are only meaningful once an upstream is tracked; an
    untracked count is a subset of the total dirty count, never larger; and
    `branch`/`detached` describe the same HEAD, so exactly one holds.
    """
    tracked = obs["upstream_tracked"]
    if (obs["ahead"] is not None) != tracked or (obs["behind"] is not None) != tracked:
        return False
    if obs["untracked_count"] > obs["dirty_count"]:
        return False
    if (obs["branch"] is None) != obs["detached"]:
        return False
    return True


GIT_SENSOR_CONTRACT = SensorContract(
    source="git_sensor",
    # Vocabulary from docs/SENSOR_AND_GOAL_MANAGER_SPEC.md plus the documented
    # fault extension. See docs/GIT_SENSOR_PHASE1.md.
    event_types=(
        "git_clean", "git_dirty", "git_ahead", "git_behind",
        "git_state_changed", "git_sensor_unavailable",
    ),
    subject_pattern=rf"^repo:(?:{IDENT}|<invalid>)$",
    observation={
        "repo":             ObservationField(str, pattern=rf"^{IDENT}$"),
        "observed_at":      ObservationField(str, pattern=RFC3339_PATTERN),
        # Repository-controlled free text: the only untrusted field.
        "branch":           ObservationField(str, nullable=True, untrusted=True),
        "detached":         ObservationField(bool),
        "head_short":       ObservationField(str, nullable=True, pattern=r"^[0-9a-f]{12}$"),
        "dirty":            ObservationField(bool),
        "dirty_count":      ObservationField(int),
        "untracked_count":  ObservationField(int),
        "upstream_tracked": ObservationField(bool),
        "ahead":            ObservationField(int, nullable=True),
        "behind":           ObservationField(int, nullable=True),
        "commit_ts":        ObservationField(int, nullable=True),
    },
    # A sensor fault is not an observation of the repository, so it is the
    # only event type allowed to omit `observation` entirely.
    observation_optional_types=("git_sensor_unavailable",),
    # `repo:<invalid>` means "the caller-supplied key was not even safe to
    # echo": that can only ever be the malformed-key fault, never a state
    # event, which by construction always has a real, allowlisted repo key.
    placeholder_subject="repo:<invalid>",
    placeholder_subject_types=("git_sensor_unavailable",),
    invariants={
        "git_clean":  lambda obs: obs["dirty"] is False and obs["dirty_count"] == 0,
        "git_dirty":  lambda obs: obs["dirty"] is True and obs["dirty_count"] > 0,
        "git_ahead":  lambda obs: obs["upstream_tracked"] is True and (obs["ahead"] or 0) > 0,
        "git_behind": lambda obs: obs["upstream_tracked"] is True and (obs["behind"] or 0) > 0,
    },
    observation_invariant=_git_observation_is_self_consistent,
)

# Static and closed. Adding a sensor means adding a contract here, in code,
# under review. There is deliberately no register() call.
SENSOR_CONTRACTS: Dict[str, SensorContract] = {
    GIT_SENSOR_CONTRACT.source: GIT_SENSOR_CONTRACT,
}


def _now_iso() -> str:
    return datetime.now(timezone.utc).astimezone().isoformat()


def _is_int(value: Any) -> bool:
    # bool is a subclass of int and must not pass as a count.
    return isinstance(value, int) and not isinstance(value, bool)


def _is_number(value: Any) -> bool:
    return (isinstance(value, (int, float)) and not isinstance(value, bool)
            and math.isfinite(value))


def build_sensor_event(
    *,
    sensor_event_type: str,
    source: str,
    subject: str,
    summary: str,
    risk: str = "low",
    confidence: float = 1.0,
    source_of_truth: Optional[List[str]] = None,
    requires_human_review: bool = False,
    suggested_next_action: str = "continue_observing",
    untrusted_fields: Optional[List[str]] = None,
    observed_at: Optional[str] = None,
    observation: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Build one validated `kagioneko.sensor_event.v1` record."""
    event = {
        "schema": SENSOR_EVENT_SCHEMA,
        "event_id": f"sensor_evt_{uuid.uuid4().hex[:16]}",
        # Constant per the Event Bus spec: the concrete observation goes in
        # `sensor_event_type`, never in `event_type`.
        "event_type": "sensor_event",
        "sensor_event_type": sensor_event_type,
        "source": source,
        "observed_at": observed_at or _now_iso(),
        "subject": subject,
        "summary": summary,
        "risk": risk,
        "confidence": confidence,
        "source_of_truth": list(source_of_truth or []),
        "requires_human_review": requires_human_review,
        "suggested_next_action": suggested_next_action,
        "untrusted_fields": list(untrusted_fields or []),
        **SAFETY_INVARIANTS,
    }
    if observation is not None:
        event["observation"] = dict(observation)
    validate_sensor_event(event)
    return event


def _validate_top_level(event: Dict[str, Any]) -> None:
    unknown = sorted(set(event) - set(FIELD_TYPES))
    if unknown:
        raise SensorEventContractError(
            f"unknown top-level fields are not part of the contract: {unknown}"
        )
    missing = [f for f in REQUIRED_FIELDS if f not in event]
    if missing:
        raise SensorEventContractError(f"missing required fields: {missing}")
    for field, expected in FIELD_TYPES.items():
        if field not in event:
            continue
        value = event[field]
        if expected is bool:
            if not isinstance(value, bool):
                raise SensorEventContractError(f"{field} must be a bool, got {value!r}")
        elif expected is float:
            if not _is_number(value):
                raise SensorEventContractError(
                    f"{field} must be a finite number, got {value!r}"
                )
        elif not isinstance(value, expected):
            raise SensorEventContractError(
                f"{field} must be {expected.__name__}, got {type(value).__name__}"
            )
    for field in ("subject", "summary", "suggested_next_action"):
        if len(event[field]) > MAX_TEXT_LEN:
            raise SensorEventContractError(f"{field} exceeds {MAX_TEXT_LEN} characters")

    if not EVENT_ID_PATTERN.match(event["event_id"]):
        raise SensorEventContractError(f"event_id is not well-formed: {event['event_id']!r}")
    observed_at = event["observed_at"]
    if len(observed_at) > MAX_OBSERVED_AT_LEN or not re.match(RFC3339_PATTERN, observed_at):
        raise SensorEventContractError(f"observed_at must be an RFC3339 timestamp, got {observed_at!r}")


def _validate_source_of_truth(entries: List[str]) -> None:
    if len(entries) > MAX_SOURCE_OF_TRUTH_ENTRIES:
        raise SensorEventContractError("too many source_of_truth entries")
    for entry in entries:
        if not isinstance(entry, str):
            raise SensorEventContractError("source_of_truth entries must be strings")
        if len(entry) > MAX_SOURCE_OF_TRUTH_LEN or not SOURCE_OF_TRUTH_PATTERN.match(entry):
            raise SensorEventContractError(
                f"source_of_truth must be a logical ptr:// pointer, got {entry!r}"
            )


def _validate_observation(contract: SensorContract, event: Dict[str, Any]) -> None:
    obs = event.get("observation")
    event_type = event["sensor_event_type"]
    if obs is None:
        if event_type not in contract.observation_optional_types:
            raise SensorEventContractError(
                f"{contract.source} event type {event_type!r} requires an observation"
            )
        return
    unknown = sorted(set(obs) - set(contract.observation))
    if unknown:
        raise SensorEventContractError(
            f"observation keys not declared by the {contract.source} contract: {unknown}"
        )
    missing = sorted(set(contract.observation) - set(obs))
    if missing:
        raise SensorEventContractError(
            f"observation is missing keys required by the {contract.source} contract: {missing}"
        )
    for key, spec in contract.observation.items():
        value = obs[key]
        if value is None:
            if not spec.nullable:
                raise SensorEventContractError(f"observation.{key} may not be null")
            continue
        if spec.type is bool:
            ok = isinstance(value, bool)
        elif spec.type is int:
            ok = _is_int(value)
        elif spec.type is float:
            ok = _is_number(value)
        else:
            ok = isinstance(value, spec.type)
        if not ok:
            raise SensorEventContractError(
                f"observation.{key} must be {spec.type.__name__}, got {value!r}"
            )
        if isinstance(value, str):
            if len(value) > MAX_OBSERVATION_STR_LEN:
                raise SensorEventContractError(
                    f"observation.{key} exceeds {MAX_OBSERVATION_STR_LEN} characters"
                )
            if spec.pattern and not spec.pattern.match(value):
                raise SensorEventContractError(
                    f"observation.{key} does not match its declared form"
                )
        if isinstance(value, int) and not isinstance(value, bool) and value < 0:
            raise SensorEventContractError(f"observation.{key} must not be negative")

    if contract.observation_invariant is not None and not contract.observation_invariant(obs):
        raise SensorEventContractError(
            f"observation for {contract.source} is internally inconsistent: {obs!r}"
        )

    invariant = contract.invariants.get(event_type)
    if invariant is not None and not invariant(obs):
        raise SensorEventContractError(
            f"observation does not satisfy the {contract.source} invariant for "
            f"{event_type!r}: {obs!r}"
        )


def _validate_provenance(contract: SensorContract, event: Dict[str, Any]) -> None:
    """`untrusted_fields` is dictated by the contract, not chosen by the producer."""
    declared = event["untrusted_fields"]
    for path in declared:
        if not isinstance(path, str):
            raise SensorEventContractError("untrusted_fields entries must be strings")
    obs = event.get("observation") or {}
    required = [
        path for path in contract.untrusted_paths
        if obs.get(path.split(".", 1)[1]) is not None
    ]
    if sorted(declared) != sorted(required):
        raise SensorEventContractError(
            f"untrusted_fields must be exactly {required} for {contract.source}, "
            f"got {declared}"
        )


def validate_sensor_event(event: Dict[str, Any]) -> None:
    """Reject anything that is not a conforming metadata-only sensor record."""
    if not isinstance(event, dict):
        raise SensorEventContractError("event must be a mapping")
    _validate_top_level(event)

    if event["schema"] != SENSOR_EVENT_SCHEMA:
        raise SensorEventContractError(f"unexpected schema: {event['schema']!r}")
    if event["event_type"] != "sensor_event":
        raise SensorEventContractError(
            f"event_type must be 'sensor_event', got {event['event_type']!r}"
        )

    contract = SENSOR_CONTRACTS.get(event["source"])
    if contract is None:
        raise SensorEventContractError(
            f"source {event['source']!r} has no sensor contract; refusing to persist"
        )
    if event["sensor_event_type"] not in contract.event_types:
        raise SensorEventContractError(
            f"{event['sensor_event_type']!r} is not in the {contract.source} vocabulary"
        )
    if not contract.subject_pattern.match(event["subject"]):
        raise SensorEventContractError(
            f"subject {event['subject']!r} does not match the {contract.source} form"
        )
    if (
        contract.placeholder_subject is not None
        and event["subject"] == contract.placeholder_subject
        and event["sensor_event_type"] not in contract.placeholder_subject_types
    ):
        raise SensorEventContractError(
            f"subject {event['subject']!r} is only valid for "
            f"{sorted(contract.placeholder_subject_types)}, got {event['sensor_event_type']!r}"
        )
    if event["risk"] not in RISK_LEVELS:
        raise SensorEventContractError(f"unknown risk level: {event['risk']!r}")
    if not 0.0 <= event["confidence"] <= 1.0:
        raise SensorEventContractError("confidence must be within 0.0..1.0")

    for field, expected in SAFETY_INVARIANTS.items():
        if event[field] is not expected:
            raise SensorEventContractError(
                f"safety field {field} must be {expected}, got {event[field]!r}"
            )

    _validate_source_of_truth(event["source_of_truth"])
    _validate_observation(contract, event)
    _validate_provenance(contract, event)


def task_tape_sink(registry, pointer_id_for: Any = None):
    """Adapter: publish conforming sensor events onto the CPOS Task Tape.

    Phase 1 substrate is `registry.audit_log` via `registry._log_event`, which
    the Event Bus spec permits as a first persistence substrate. The record
    written is the sensor envelope itself, so swapping the substrate later does
    not change the contract. Validation runs here as well as in the builder,
    because the adapter is the boundary any producer crosses: a record built by
    hand or by another sensor is refused rather than persisted.
    """
    def _sink(event: Dict[str, Any]) -> None:
        validate_sensor_event(event)
        pointer_id = (
            pointer_id_for(event) if callable(pointer_id_for)
            else (pointer_id_for or event["source"])
        )
        registry._log_event(TAPE_SENSOR_EVENT, pointer_id, event)
    return _sink
